-- Disable foreign key constraints
SET REFERENTIAL_INTEGRITY FALSE;

-- Clean up test database by deleting all data from tables
DELETE FROM INFORME;
DELETE FROM IMAGEN;
DELETE FROM PACIENTE;
DELETE FROM MEDICO;

-- Reset auto-increment sequences for H2
ALTER TABLE MEDICO ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE PACIENTE ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE IMAGEN ALTER COLUMN ID RESTART WITH 1;
ALTER TABLE INFORME ALTER COLUMN ID RESTART WITH 1;

-- Re-enable foreign key constraints
SET REFERENTIAL_INTEGRITY TRUE;

